default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TCV_DB_USER'] %>
  password: <%= ENV['TCV_DB_PASSWORD'] %>
  host: <%= ENV['TCV_DB_HOST'] %>
  port: <%= ENV['TCV_DB_PORT'] %>


development:
  <<: *default
  database: twitter_comic_viewer_development

test:
  <<: *default
  database: twitter_comic_viewer_test

production:
  <<: *default
  database: twitter_comic_viewer_production
